# Generated by Django 5.2.1 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapport",
            name="statut",
            field=models.CharField(
                choices=[
                    ("attente", "En attente"),
                    ("valide", "Validé"),
                    ("refuse", "Refusé"),
                ],
                default="attente",
                max_length=20,
            ),
        ),
    ]
