# Generated by Django 5.2.1 on 2026-05-06 14:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapports", "0002_rapport_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapport",
            name="fichier",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="fichier"
            ),
        ),
        migrations.AlterField(
            model_name="rapport",
            name="contenu",
            field=models.TextField(blank=True),
        ),
    ]
