# Generated by Django 5.2.1 on 2026-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapports", "0003_rapport_fichier_alter_rapport_contenu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rapport",
            name="fichier",
        ),
        migrations.AddField(
            model_name="rapport",
            name="fichier_nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rapport",
            name="fichier_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
