# Generated by Django 5.2.1 on 2026-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapports", "0004_remove_rapport_fichier_rapport_fichier_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapport",
            name="fichier_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
