# Generated by Django 5.2.13 on 2026-04-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("ecole", models.CharField(default="Non spécifié", max_length=200)),
                (
                    "type_pointage",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                    ),
                ),
                ("heure", models.CharField(max_length=10)),
                ("wa_envoye", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "pointages",
                "ordering": ["-timestamp"],
            },
        ),
    ]
