# Generated by Django 5.2.13 on 2026-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presences", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointage",
            name="ecole",
        ),
        migrations.AddField(
            model_name="pointage",
            name="email",
            field=models.EmailField(default="", max_length=200),
        ),
    ]
