# Generated by Django 5.2.13 on 2026-04-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presences", "0002_remove_pointage_ecole_pointage_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("justifiee", models.BooleanField(default=False)),
                (
                    "justification",
                    models.FileField(
                        blank=True, null=True, upload_to="justifications/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "absences",
                "unique_together": {("nom", "prenom", "date")},
            },
        ),
    ]
