# Generated by Django 5.2.13 on 2026-04-20 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presences", "0003_absence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="absence",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="absence",
            name="stagiaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="absence",
            unique_together={("stagiaire", "date")},
        ),
    ]
