# Generated by Django 5.2.13 on 2026-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="responsable_nom",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="projet",
            name="tasks_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
