# Generated by Django 5.2.1 on 2026-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to="cv/", verbose_name="CV"
            ),
        ),
    ]
