# Generated by Django 5.2.13 on 2026-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_debut_stage",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date début stage"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_fin_stage",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date fin stage"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ecole",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="École"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="formation",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Formation"
            ),
        ),
    ]
