# Generated by Django 5.2.13 on 2026-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_date_debut_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="departement",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Département"
            ),
        ),
    ]
