# Generated by Django 5.2.13 on 2026-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_departement"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="absences_non_justifiees",
            field=models.IntegerField(
                default=0, verbose_name="Absences non justifiées"
            ),
        ),
    ]
