# Generated by Django 5.2 on 2026-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_absences_non_justifiees"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Accepté", "Accepté"),
                    ("En attente", "En attente"),
                    ("Refusé", "Refusé"),
                ],
                default="Accepté",
                max_length=20,
            ),
        ),
    ]
