# Generated by Django 5.2.13 on 2026-05-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mot_de_passe_clair",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
