# Generated by Django 5.2.1 on 2026-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_mot_de_passe_clair"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cv_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CV Nom"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cv_public_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CV Public ID"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cv_url",
            field=models.URLField(blank=True, null=True, verbose_name="CV URL"),
        ),
    ]
